### PR TITLE
Add support to enforce SSL requests

### PR DESCRIPTION
**Pull request by diego-ojeda-binbash**
## what
* Add support to enforce SSL requests

## why
* It is a recommended security best practice usually enforced by AWS Config

### CODE REVIEW

**Review by exequielrafaela — CHANGES_REQUESTED** [review]
@diego-ojeda-binbash OJ tests are not passing. I'll try to commit the fix in order to collaborate here :muscle:

**Review by exequielrafaela — APPROVED** [review]
@diego-ojeda-binbash I've done several test related updates. All the test-cases aren't passing yet, we can work this out in another ticket though.

**Comment by exequielrafaela** [comment]
@diego-ojeda-binbash OJ with terraform aws provider >= 3.0 we algo get the issue reported for https://github.com/binbashar/terraform-aws-vpc-flowlogs/issues/7

I'll also move forward with this upgrade and fix :heavy_check_mark:

**Comment by diego-ojeda-binbash** [comment]
> @diego-ojeda-binbash OJ with terraform aws provider >= 3.0 we algo get the issue reported for [binbashar/terraform-aws-vpc-flowlogs#7](https://github.com/binbashar/terraform-aws-vpc-flowlogs/issues/7)
> 
> I'll also move forward with this upgrade and fix ✔️

@exequielrafaela Thanks for your help here!

**Pull request merged**
