### PR TITLE
ci: scan the module with aquasec's tfsec

### PR DESCRIPTION
**Pull request by d3adb5**
## what

* The module is now scanned with tfsec every time a PR is opened or merged.
* Some issues pointed out by tfsec are ignored, as they are deemed false
  positives. The reasoning is documented in the commit message that ignores
  them: cc44cc5

## why

* This change adds additional security guarantees to the module, and
  consequently to its users.

## references

* Built on top of #23, will remain a draft until that PR is merged.

### CODE REVIEW

**Comment by d3adb5** [comment]
I'm not sure what CI processes are in place for this repository, but since other than GitGuardian's none appear over here, I assumed there weren't any. GitHub Actions is currently free for all public repositories, so I took the opportunity of adding a workflow to run tfsec.

It won't run until given approval by an organization admin, I believe. Either that or until a PR is opened by a previously authorized account with the workflow in it. I've seen other organizations open a PR of their own to test it out before merging it. Not sure if there's something I'm missing in working with GitHub Actions.

**Comment by d3adb5** [comment]
Silly me. I just saw CircleCI is being used. :facepalm: I'm closing this PR for now, but will work on adding tfsec to the CircleCI pipeline.

**Comment by d3adb5** [comment]
Not much of a CircleCI guy, this might not work. If it doesn't, I'd really like to know why. :eyes:

**Comment by eze-godoy** [comment]
Hi there @d3adb5! Thanks for your contributions. As you mentioned we currently use CircleCI, but we want to encourage GitHub Actions in the future. Maybe this is a good opportunity to start with this repo.

**Comment by d3adb5** [comment]
Thanks for taking a look, @eze-godoy! In that case, should I restore the PR as it originally was, adding a GitHub Actions workflow? How should we move forward?

**Comment by eze-godoy** [comment]
Hi @d3adb5! I think it would be better to restore the PR and add the GitHub Actions workflow.

**Comment by d3adb5** [comment]
@eze-godoy Done!

**Comment by eze-godoy** [comment]
Hello, @d3adb5. As our static code analysis tool, we will use [Checkov](https://github.com/bridgecrewio/checkov). I'm sorry that we won't be able to merge this PR. We value your contributions and interest in our modules.

**Pull request closed without merging**
